/*
** DON'T EDIT THIS FILE **
It's been generated by Zapatos, and is liable to be overwritten

Zapatos: https://jawj.github.io/zapatos/
Copyright (C) 2020 - 2022 George MacKerron
Released under the MIT licence: see LICENCE file
*/

declare module 'zapatos/schema' {

  import type * as db from 'zapatos/db';

  // got a type error on schemaVersionCanary below? update by running `npx zapatos`
  export interface schemaVersionCanary extends db.SchemaVersionCanary { version: 104 }


  /* === schema: public === */

  /* --- enums --- */
  /* (none) */

  /* --- tables --- */

  /**
   * **posts**
   * - Table in database
   */
  export namespace posts {
    export type Table = 'posts';
    export interface Selectable {
      /**
      * **posts.post_id**
      * - `uuid` in database
      * - `NOT NULL`, default: `gen_random_uuid()`
      */
    post_id: string;
      /**
      * **posts.user_id**
      * - `uuid` in database
      * - `NOT NULL`, no default
      */
    user_id: string;
      /**
      * **posts.body**
      * - `text` in database
      * - `NOT NULL`, no default
      */
    body: string;
      /**
      * **posts.created_at**
      * - `timestamptz` in database
      * - `NOT NULL`, default: `now()`
      */
    created_at: Date;
    }
    export interface JSONSelectable {
      /**
      * **posts.post_id**
      * - `uuid` in database
      * - `NOT NULL`, default: `gen_random_uuid()`
      */
    post_id: string;
      /**
      * **posts.user_id**
      * - `uuid` in database
      * - `NOT NULL`, no default
      */
    user_id: string;
      /**
      * **posts.body**
      * - `text` in database
      * - `NOT NULL`, no default
      */
    body: string;
      /**
      * **posts.created_at**
      * - `timestamptz` in database
      * - `NOT NULL`, default: `now()`
      */
    created_at: db.TimestampTzString;
    }
    export interface Whereable {
      /**
      * **posts.post_id**
      * - `uuid` in database
      * - `NOT NULL`, default: `gen_random_uuid()`
      */
    post_id?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **posts.user_id**
      * - `uuid` in database
      * - `NOT NULL`, no default
      */
    user_id?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **posts.body**
      * - `text` in database
      * - `NOT NULL`, no default
      */
    body?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **posts.created_at**
      * - `timestamptz` in database
      * - `NOT NULL`, default: `now()`
      */
    created_at?: (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | db.SQLFragment | db.ParentColumn>;
    }
    export interface Insertable {
      /**
      * **posts.post_id**
      * - `uuid` in database
      * - `NOT NULL`, default: `gen_random_uuid()`
      */
    post_id?: string | db.Parameter<string> | db.DefaultType | db.SQLFragment;
      /**
      * **posts.user_id**
      * - `uuid` in database
      * - `NOT NULL`, no default
      */
    user_id: string | db.Parameter<string> | db.SQLFragment;
      /**
      * **posts.body**
      * - `text` in database
      * - `NOT NULL`, no default
      */
    body: string | db.Parameter<string> | db.SQLFragment;
      /**
      * **posts.created_at**
      * - `timestamptz` in database
      * - `NOT NULL`, default: `now()`
      */
    created_at?: (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | db.DefaultType | db.SQLFragment;
    }
    export interface Updatable {
      /**
      * **posts.post_id**
      * - `uuid` in database
      * - `NOT NULL`, default: `gen_random_uuid()`
      */
    post_id?: string | db.Parameter<string> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.DefaultType | db.SQLFragment>;
      /**
      * **posts.user_id**
      * - `uuid` in database
      * - `NOT NULL`, no default
      */
    user_id?: string | db.Parameter<string> | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment>;
      /**
      * **posts.body**
      * - `text` in database
      * - `NOT NULL`, no default
      */
    body?: string | db.Parameter<string> | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment>;
      /**
      * **posts.created_at**
      * - `timestamptz` in database
      * - `NOT NULL`, default: `now()`
      */
    created_at?: (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | db.DefaultType | db.SQLFragment>;
    }
    export type UniqueIndex = 'posts_pkey';
    export type Column = keyof Selectable;
    export type OnlyCols<T extends readonly Column[]> = Pick<Selectable, T[number]>;
    export type SQLExpression = Table | db.ColumnNames<Updatable | (keyof Updatable)[]> | db.ColumnValues<Updatable> | Whereable | Column | db.ParentColumn | db.GenericSQLExpression;
    export type SQL = SQLExpression | SQLExpression[];
  }

  /**
   * **users**
   * - Table in database
   */
  export namespace users {
    export type Table = 'users';
    export interface Selectable {
      /**
      * **users.user_id**
      * - `uuid` in database
      * - `NOT NULL`, default: `gen_random_uuid()`
      */
    user_id: string;
      /**
      * **users.username**
      * - `citext` in database
      * - `NOT NULL`, no default
      */
    username: string;
      /**
      * **users.password_hash**
      * - `text` in database
      * - `NOT NULL`, no default
      */
    password_hash: string;
      /**
      * **users.created_at**
      * - `timestamptz` in database
      * - `NOT NULL`, default: `now()`
      */
    created_at: Date;
    }
    export interface JSONSelectable {
      /**
      * **users.user_id**
      * - `uuid` in database
      * - `NOT NULL`, default: `gen_random_uuid()`
      */
    user_id: string;
      /**
      * **users.username**
      * - `citext` in database
      * - `NOT NULL`, no default
      */
    username: string;
      /**
      * **users.password_hash**
      * - `text` in database
      * - `NOT NULL`, no default
      */
    password_hash: string;
      /**
      * **users.created_at**
      * - `timestamptz` in database
      * - `NOT NULL`, default: `now()`
      */
    created_at: db.TimestampTzString;
    }
    export interface Whereable {
      /**
      * **users.user_id**
      * - `uuid` in database
      * - `NOT NULL`, default: `gen_random_uuid()`
      */
    user_id?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **users.username**
      * - `citext` in database
      * - `NOT NULL`, no default
      */
    username?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **users.password_hash**
      * - `text` in database
      * - `NOT NULL`, no default
      */
    password_hash?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **users.created_at**
      * - `timestamptz` in database
      * - `NOT NULL`, default: `now()`
      */
    created_at?: (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | db.SQLFragment | db.ParentColumn>;
    }
    export interface Insertable {
      /**
      * **users.user_id**
      * - `uuid` in database
      * - `NOT NULL`, default: `gen_random_uuid()`
      */
    user_id?: string | db.Parameter<string> | db.DefaultType | db.SQLFragment;
      /**
      * **users.username**
      * - `citext` in database
      * - `NOT NULL`, no default
      */
    username: string | db.Parameter<string> | db.SQLFragment;
      /**
      * **users.password_hash**
      * - `text` in database
      * - `NOT NULL`, no default
      */
    password_hash: string | db.Parameter<string> | db.SQLFragment;
      /**
      * **users.created_at**
      * - `timestamptz` in database
      * - `NOT NULL`, default: `now()`
      */
    created_at?: (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | db.DefaultType | db.SQLFragment;
    }
    export interface Updatable {
      /**
      * **users.user_id**
      * - `uuid` in database
      * - `NOT NULL`, default: `gen_random_uuid()`
      */
    user_id?: string | db.Parameter<string> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.DefaultType | db.SQLFragment>;
      /**
      * **users.username**
      * - `citext` in database
      * - `NOT NULL`, no default
      */
    username?: string | db.Parameter<string> | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment>;
      /**
      * **users.password_hash**
      * - `text` in database
      * - `NOT NULL`, no default
      */
    password_hash?: string | db.Parameter<string> | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment>;
      /**
      * **users.created_at**
      * - `timestamptz` in database
      * - `NOT NULL`, default: `now()`
      */
    created_at?: (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, (db.TimestampTzString | Date) | db.Parameter<(db.TimestampTzString | Date)> | db.DefaultType | db.SQLFragment>;
    }
    export type UniqueIndex = 'users_pkey' | 'users_username_key';
    export type Column = keyof Selectable;
    export type OnlyCols<T extends readonly Column[]> = Pick<Selectable, T[number]>;
    export type SQLExpression = Table | db.ColumnNames<Updatable | (keyof Updatable)[]> | db.ColumnValues<Updatable> | Whereable | Column | db.ParentColumn | db.GenericSQLExpression;
    export type SQL = SQLExpression | SQLExpression[];
  }

  /* --- aggregate types --- */

  export namespace public {  
    export type Table = posts.Table | users.Table;
    export type Selectable = posts.Selectable | users.Selectable;
    export type JSONSelectable = posts.JSONSelectable | users.JSONSelectable;
    export type Whereable = posts.Whereable | users.Whereable;
    export type Insertable = posts.Insertable | users.Insertable;
    export type Updatable = posts.Updatable | users.Updatable;
    export type UniqueIndex = posts.UniqueIndex | users.UniqueIndex;
    export type Column = posts.Column | users.Column;
  
    export type AllBaseTables = [posts.Table, users.Table];
    export type AllForeignTables = [];
    export type AllViews = [];
    export type AllMaterializedViews = [];
    export type AllTablesAndViews = [posts.Table, users.Table];
  }



  /* === global aggregate types === */

  export type Schema = 'public';
  export type Table = public.Table;
  export type Selectable = public.Selectable;
  export type JSONSelectable = public.JSONSelectable;
  export type Whereable = public.Whereable;
  export type Insertable = public.Insertable;
  export type Updatable = public.Updatable;
  export type UniqueIndex = public.UniqueIndex;
  export type Column = public.Column;

  export type AllSchemas = ['public'];
  export type AllBaseTables = [...public.AllBaseTables];
  export type AllForeignTables = [...public.AllForeignTables];
  export type AllViews = [...public.AllViews];
  export type AllMaterializedViews = [...public.AllMaterializedViews];
  export type AllTablesAndViews = [...public.AllTablesAndViews];


  /* === lookups === */

  export type SelectableForTable<T extends Table> = {
    "posts": posts.Selectable;
    "users": users.Selectable;
  }[T];

  export type JSONSelectableForTable<T extends Table> = {
    "posts": posts.JSONSelectable;
    "users": users.JSONSelectable;
  }[T];

  export type WhereableForTable<T extends Table> = {
    "posts": posts.Whereable;
    "users": users.Whereable;
  }[T];

  export type InsertableForTable<T extends Table> = {
    "posts": posts.Insertable;
    "users": users.Insertable;
  }[T];

  export type UpdatableForTable<T extends Table> = {
    "posts": posts.Updatable;
    "users": users.Updatable;
  }[T];

  export type UniqueIndexForTable<T extends Table> = {
    "posts": posts.UniqueIndex;
    "users": users.UniqueIndex;
  }[T];

  export type ColumnForTable<T extends Table> = {
    "posts": posts.Column;
    "users": users.Column;
  }[T];

  export type SQLForTable<T extends Table> = {
    "posts": posts.SQL;
    "users": users.SQL;
  }[T];

}
